### PR TITLE
Fix power flow initialisation of synchronous generators

### LINKED ISSUE #223: Fix power flow initialisation & updating for the terminals
- The terminals of the components are not correctly initialized with initial power and updated with power flow solutions. This might lead to an initialization error in the dynamic simulation (if the terminal power is used in _initializeFromNodesAndTerminals_ e.g. _terminal(0)->singlePower()_)

### PR DESCRIPTION
**Pull request by martinmoraga**
In powerflow simulations, the power of synchronous generators is not being always correctly calculated, since the power of the loads connected to nodes is not considered in the calculation. This PR fixes the calculation of the synchronous generators' power in powerflow simulations and adapts the funcion `initWithPowerFlow` to initialialize the terminal power of the synchronous generators after the powerflow calculation.

Closes #223

### CODE REVIEW

File: dpsim/src/PFSolverPowerPolar.cpp [hunk 1]
```diff
@@ -353,47 +368,96 @@ Real PFSolverPowerPolar::Q(UInt k) {
...
+        for (UInt j = 0; j < mSystem.mNodes.size(); ++j)
+            I += mY.coeff(node_idx, j) * sol_Vcx(j);
+        CPS::Complex S = sol_Vcx(node_idx) * conj(I);
+
+        // GenPower = Power flowing out of node + PQLoadsPower
+        for(auto comp : mSystem.mComponentsAtNode[topoNode])
+            if (auto loadPtr = std::dynamic_pointer_cast<CPS::SP::Ph1::Load>(comp))
+                S += Complex(**(loadPtr->mActivePowerPerUnit), **(loadPtr->mReactivePowerPerUnit));
+
+        // Set power of external network injections of SG (VD)
```
Comment (dinkelbachjan) [inline dpsim/src/PFSolverPowerPolar.cpp:385]: @martinmoraga 
`// Set power of either VD-type external network injection or VD-type synchronous generator depending on what is connected`
Is this is what you mean here?

File: dpsim/src/PFSolverPowerPolar.cpp
Comment (dinkelbachjan) [inline dpsim/src/PFSolverPowerPolar.cpp:1]: It should be reconsidered what we eventually store in `sol_P` and `sol_Q`, as described in more detail in the respective TODO comment lines of his file. Besides, we could consider combining `calculatePAndQAtSlackBus` , `calculateQAtPVBuses` und `calculatePAndQInjectionPQBuses`.

**Review by dinkelbachjan — APPROVED** [review]

File: dpsim/src/PFSolverPowerPolar.cpp
Comment (dinkelbachjan) [reply dpsim/src/PFSolverPowerPolar.cpp:1]: This will not be covered by this PR, but instead will be followed up on by closing #266.
